name: Sync Repo Settings
on:
  push:
    branches:
      - main
      - chore/repo_settings_sync
  schedule:
    # once a day at 8am
    - cron:  "0 8 * * *"
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - uses: actions/checkout@v3
        with:
          repository: googleapis/repo-automation-bots
          path: repo-automation-bots

      - name: Install sync-repo-settings
        run: |
          cd repo-automation-bots/packages/sync-repo-settings
          npm i
          npm run compile

      - name: Sync repos settings
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_SYNC_SETTINGS_TOKEN }}
        run: |
          shopt -s expand_aliases
          alias sync-repo-settings='node repo-automation-bots/packages/sync-repo-settings/build/src/cli.js'

          # core and sdk
          sync-repo-settings --repo=cloudquery/cloudquery --file=repo-settings/cloudquery/config.yaml
          sync-repo-settings --repo=cloudquery/cq-provider-sdk --file=repo-settings/cq-provider-sdk/config.yaml

          # providers
          sync-repo-settings --repo=cloudquery/cq-provider-digitalocean --file=repo-settings/providers/config.yaml
          sync-repo-settings --repo=cloudquery/cq-provider-k8s --file=repo-settings/providers/config.yaml
          sync-repo-settings --repo=cloudquery/cq-provider-okta --file=repo-settings/providers/config.yaml
          sync-repo-settings --repo=cloudquery/cq-provider-template --file=repo-settings/providers/config.yaml

          # providers with terraform
          sync-repo-settings --repo=cloudquery/cq-provider-aws --file=repo-settings/providers-with-terraform/config.yaml
          sync-repo-settings --repo=cloudquery/cq-provider-azure --file=repo-settings/providers-with-terraform/config.yaml
          sync-repo-settings --repo=cloudquery/cq-provider-gcp --file=repo-settings/providers-with-terraform/config.yaml

          # policies
          sync-repo-settings --repo=cloudquery-policies/aws --file=repo-settings/policies/config.yaml
          sync-repo-settings --repo=cloudquery-policies/gcp --file=repo-settings/policies/config.yaml
          sync-repo-settings --repo=cloudquery-policies/azure --file=repo-settings/policies/config.yaml
          sync-repo-settings --repo=cloudquery-policies/k8s --file=repo-settings/policies/config.yaml